Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -40,15 +40,9 @@ jobs:
         run: git log -1
 
       - name: Commit and push changes
+        env:
+          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
         run: |
           git add images/github-contribution-grid-snake.svg
           git commit -m "Generate snake.svg"
-          git push origin main || echo "Git push failed"
-        env:
-          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
-
-      - name: Check GITHUB_TOKEN permissions
-        run: |
-          curl -H "Authorization: token ${{ secrets.MY_GITHUB_TOKEN }}" \
-          -H "Accept: application/vnd.github.v3+json" \
-          https://api.github.com/repos/Atome1212/Atome1212
+          git push https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/Atome1212/Atome1212.git main || echo "Git push failed"
