Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,29 +1,54 @@
 name: Generate Snake
 
 on:
-  workflow_dispatch:
   schedule:
-    - cron: "0 0 * * *"
+    - cron: "0 0 * * *" # runs at midnight every day
+  workflow_dispatch: # Allows you to manually trigger the workflow from the Actions tab
 
 jobs:
   build:
     runs-on: ubuntu-latest
+
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v2
+      - name: Checkout repository
+        uses: actions/checkout@v3
+        with:
+          ref: main
 
-    - name: Generate snake.svg
-      uses: Platane/snk@v2
-      env:
-        GITHUB_USER_NAME: Atome1212  # Assurez-vous que c'est bien votre nom d'utilisateur GitHub
-        OUTPUT: dist/snake.svg  # Correction de la clé "output" au lieu de "outputs"
+      - name: Create images directory
+        run: mkdir -p images
 
-    - name: Commit and Push
-      env:
-        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
-      run: |
-        git config --global user.email "actions@github.com"
-        git config --global user.name "GitHub Actions"
-        git add dist/snake.svg
-        git commit -m "Generate snake.svg"
-        git push origin main
+      - name: Generate Snake
+        uses: Platane/snk@v2.0.0-rc.2
+        with:
+          github_user_name: Atome1212
+          outputs: images/github-contribution-grid-snake.svg
+
+      - name: List images directory for debugging
+        run: ls -R images
+
+      - name: Configure Git
+        run: |
+          git config --global user.name 'github-actions[bot]'
+          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
+          git config --global --add safe.directory /github/workspace
+
+      - name: Debug Git Status
+        run: git status
+
+      - name: Show Git Log
+        run: git log -1
+
+      - name: Commit and push changes
+        run: |
+          git add images/github-contribution-grid-snake.svg
+          git commit -m "Generate snake.svg"
+          git push origin main || echo "Git push failed"
+        env:
+          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
+
+      - name: Check GITHUB_TOKEN permissions
+        run: |
+          curl -H "Authorization: token ${{ secrets.MY_GITHUB_TOKEN }}" \
+          -H "Accept: application/vnd.github.v3+json" \
+          https://api.github.com/repos/Atome1212/Atome1212
